#!/bin/bash

DOTFILES="${HOME}/.dotfiles"            # Base it on `pwd'!
DOTHOME=${DOTFILES}/home


# Make a backup directory for overwritten dotfiles.
if [[ ! -e ~/.dotfiles/backup ]]; then
    mkdir ~/.dotfiles/backup
fi


cd $DOTHOME

for config_file in $(ls --almost-all)
do
    config_file=$(basename $config_file)
    echo "Symlinking $config_file..."
    ln -s ${DOTHOME}/$config_file ${HOME}/$config_file
done
