#!/bin/bash

DOTFILES="${HOME}/.dotfiles"
cd ${DOTFILES}/files

for f in $(find -type f)
do
    f=$(basename $f)
    ln -s ${DOTFILES}/files/$f ${HOME}/$f
done

# ln -s ${DOTFILES}/.zshrc ${HOME}/.zshrc
# ln -s ${DOTFILES}/.gitconfig ${HOME}/.gitconfig
