#!/usr/bin/env sh

VALUE_ICON=$(cygpath -d "/cygdrive/c/cygwin64/usr/share/texmf-dist/tex/latex/alertmessage/img/alertmessage-info.png")
VALUE_TITLE="Terminal"
VALUE_MESSAGE="<empty>"

while getopts hi:t:m: OPT
do
    case $OPT in
        "i" ) FLG_ICON="TRUE" ; VALUE_ICON="$(cygpath -d $OPTARG)" ;;
        "t" ) FLG_TITLE="TRUE" ; VALUE_TITLE="$OPTARG" ;;
        "m" ) FLG_MESSAGE="TRUE" ; VALUE_MESSAGE="$OPTARG" ;;
        "h" ) echo "Usage: notify-send [options of 'growl for windows' ...] message" ; exit 0 ;;
    esac
done

/cygdrive/c/Program\ Files\ \(x86\)/Growl\ for\ Windows/growlnotify.com /i:"$VALUE_ICON" /t:"$VALUE_TITLE" "$VALUE_MESSAGE"

