#!/bin/sh
# Copyright (C) 2002, Earnie Boyd
#   mailto:earnie@users.sf.net
# This file is part of Minimal SYStem.
#   http://www.mingw.org/msys.shtml
# File: start

cmd /c start $(cygpath -w "$@")

# See https://github.com/babun/babun/issues/299#issuecomment-123925935
# for registering your applications in Windows and autocompleting file names
